repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks: [{id: ruff}]
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks: [{id: black, args: ["--check"]}]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks: [{id: mypy}]
- repo: https://github.com/pypa/pip-audit
  rev: v2.7.3
  hooks: [{id: pip-audit, args: ["-r","requirements.txt"], language_version: python3}]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks: [{id: gitleaks, args: ["protect","--verbose","--redact"]}]
