version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: nifty-scalper:latest
    container_name: nifty-scalper
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Ensure IST inside container (also set in Dockerfile)
      - TZ=Asia/Kolkata
      # Optional: override mode at runtime
      # - ENABLE_LIVE_TRADING=false  # default is true
      # - ENABLE_TELEGRAM=true
    volumes:
      # Persist logs locally (optional)
      - ./logs:/app/logs
    command: ["python", "-m", "src.main"]
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Run the test suite inside a container
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: nifty-scalper:latest
    profiles: ["test"]
    env_file:
      - .env
    working_dir: /app
    command: ["pytest"]
