[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.ruff]
target-version = "py311"
line-length = 88
exclude = ["data", "build", "dist", ".venv", ".git"]

[tool.ruff.lint]
# Keep Ruff focused on correctness & modernization (leave import ordering to isort)
exclude = ["data", "build", "dist", ".venv", ".git"]
select = []
ignore = []

[tool.ruff.lint.per-file-ignores]
# Tests often use asserts and looser patterns—treat them gently
"tests/**" = ["SIM"]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--cov=src --cov-report=term-missing"
