[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
include_trailing_comma = true

[tool.ruff]
target-version = "py311"
line-length = 100
exclude = ["data", "build", "dist", ".venv", ".git"]

[tool.ruff.lint]
# Keep Ruff focused on correctness & modernization (leave import ordering to isort)
exclude = ["data", "build", "dist", ".venv", ".git"]
extend-select = ["F", "E", "W", "I", "UP", "B", "SIM", "ERA"]
ignore = ["E402", "E501", "SIM102", "SIM105", "SIM108", "UP007", "UP038"]

[tool.ruff.lint.isort]
known-first-party = ["src"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.per-file-ignores]
# Tests often use asserts and looser patterns—treat them gently
"tests/**" = ["SIM"]
"src/strategies/runner.py" = ["E501", "SIM105", "SIM102", "UP038"]
"src/utils/log_filters.py" = ["E402"]
"src/utils/logger_setup.py" = ["E402"]
"src/utils/retry.py" = ["SIM105"]
"src/utils/strike_selector.py" = ["UP038"]
"src/utils/structured_logger.py" = ["E501", "SIM108"]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-q --maxfail=1 --disable-warnings --cov=src --cov-report=term-missing"
testpaths = ["tests"]
