[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
include_trailing_comma = true

[tool.ruff]
target-version = "py311"
line-length = 88
# Keep Ruff focused on correctness & modernization (leave import ordering to isort)
select = ["E", "F", "B", "UP", "SIM", "RUF"]
ignore = []
exclude = ["data", "build", "dist", ".venv", ".git"]

[tool.ruff.lint.per-file-ignores]
# Tests often use asserts and looser patterns—treat them gently
"tests/**" = ["SIM"]

[tool.pytest.ini_options]
pythonpath = "."
