services:
  - type: web
    name: nifty-options-trader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ZERODHA_API_KEY
        sync: false
      - key: ZERODHA_API_SECRET
        sync: false
      - key: ZERODHA_ACCESS_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TRADING_ENABLED
        value: "false"
      - key: ACCOUNT_SIZE
        value: "100000"
      - key: LOG_LEVEL
        value: "INFO"
      - key: CHECK_INTERVAL
        value: "300"

databases:
  - name: nifty-trader-db
    databaseName: nifty_trader
    user: nifty_user