target-version = "py310"
extend-exclude = ["tests/**"]

[lint]
# Keep important errors; temporarily relax some style rules you hit a lot
ignore = [
  "E402",  # imports not at top (common in tests/scripts)
  "E701", "E702", # multiple statements on a line (we'll clean later)
  "E741",        # ambiguous var names like 'l' (clean later)
]
select = ["E", "F"]

[format]
line-length = 100
