target-version = "py310"
line-length = 100

[lint]
# TEMPORARY ignores to unblock CI quickly
ignore = [
  "E402",  # imports not at top (common in tests/scripts)
  "E701", "E702",  # multiple statements on a line
  "E741",          # ambiguous names like 'l'
  "F401",          # imported but unused
  "F821",          # undefined name (we'll fix properly later)
  "F841",          # local var assigned but never used
]
select = ["E", "F"]
