"""Runtime status/log hygiene for non-gating startup observations.

This module does not change trading decisions. It corrects observability defects
that made the admin console show false errors after a healthy market-closed
startup:

* non-selected option-context hydration attempts are expected to skip broker
  fetches when the market is closed; those records must not be counted as ERRORs.
* position reconciliation completion may be visible in runtime logs before the
  lightweight admin process receives a structured completed flag; status helpers
  should reconcile that from the same bounded log window they already read.
"""

from __future__ import annotations

import logging
from typing import Any, Mapping

_GENERIC_HISTORY_EVENT = "CANONICAL_HISTORY_RESULT"
_SOFT_FAILURE_REASONS = {"broker_fetch_not_allowed"}
_SOFT_ROLES = {"option_context"}
_PATCHED = False


def _record_mapping(record: logging.LogRecord) -> Mapping[str, Any]:
    return getattr(record, "__dict__", {}) or {}


def is_soft_non_gating_history_record(record: logging.LogRecord) -> bool:
    """Return True for expected non-selected context hydration misses.

    The runtime still emits the diagnostic, but the level is downgraded from
    ERROR to INFO so admin/error counters do not report a false production error.
    """

    data = _record_mapping(record)
    event = str(data.get("event") or "")
    message = ""
    try:
        message = record.getMessage()
    except Exception:  # pragma: no cover - defensive logging boundary
        message = str(getattr(record, "msg", "") or "")
    if event != _GENERIC_HISTORY_EVENT and _GENERIC_HISTORY_EVENT not in message:
        return False
    role = str(data.get("role") or "")
    failure = str(data.get("failure_reason") or "")
    if role in _SOFT_ROLES and failure in _SOFT_FAILURE_REASONS:
        return True
    # The plain-text log line generated by the structured logger carries these
    # fields inside the message; support that path as well.
    return (
        "role=option_context" in message
        and "failure_reason=broker_fetch_not_allowed" in message
    )


class CanonicalHistorySoftFailureFilter(logging.Filter):
    """Downgrade expected non-gating option-context history misses."""

    def filter(self, record: logging.LogRecord) -> bool:
        if record.levelno >= logging.ERROR and is_soft_non_gating_history_record(record):
            record.levelno = logging.INFO
            record.levelname = logging.getLevelName(logging.INFO)
            record.soft_non_gating = True
            record.gating = False
        return True


def apply_logging_filters() -> bool:
    """Install log-level hygiene filters once. Returns True when installed."""

    global _PATCHED
    if _PATCHED:
        return False
    filt = CanonicalHistorySoftFailureFilter()
    targets = [
        logging.getLogger(),
        logging.getLogger("nifty_scalper_bot.core.app"),
        logging.getLogger("nifty_scalper_bot.core.history_readiness"),
    ]
    for logger in targets:
        if not any(isinstance(existing, CanonicalHistorySoftFailureFilter) for existing in logger.filters):
            logger.addFilter(filt)
    _PATCHED = True
    return True


def infer_reconciliation_complete_from_logs(log_text: str) -> bool:
    """Infer successful reconciliation from bounded runtime logs.

    This is intentionally conservative: a RECONCILE_COMPLETE marker must appear
    after a RECONCILE_START marker, and no explicit failure marker may appear
    after that start.
    """

    lines = list(str(log_text or "").splitlines())
    start_index: int | None = None
    complete_index: int | None = None
    for idx, line in enumerate(lines):
        if "RECONCILE_START" in line:
            start_index = idx
            complete_index = None
        if "RECONCILE_COMPLETE" in line and start_index is not None:
            complete_index = idx
    if start_index is None or complete_index is None or complete_index < start_index:
        return False
    tail = "\n".join(lines[start_index:])
    failure_tokens = (
        "POSITION_RECONCILE_FAILED",
        "RECONCILE_FAILED",
        "reconcile.failed",
    )
    return not any(token in tail for token in failure_tokens)


__all__ = [
    "CanonicalHistorySoftFailureFilter",
    "apply_logging_filters",
    "infer_reconciliation_complete_from_logs",
    "is_soft_non_gating_history_record",
]
