"""Prometheus metrics definitions."""

from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, start_http_server  # type: ignore[import]


class BotMetrics:
    def __init__(self) -> None:
        self.signals_generated = Counter(
            "nifty_signals_generated_total",
            "Signals generated by strategies",
            ["strategy", "direction"],
        )
        self.orders_placed = Counter(
            "nifty_orders_placed_total",
            "Orders placed",
            ["mode", "status"],
        )
        self.pnl_realized = Gauge(
            "nifty_pnl_realized_inr",
            "Realized daily P&L in INR",
        )
        self.open_positions = Gauge(
            "nifty_open_positions",
            "Currently open positions",
        )
        self.loop_duration = Histogram(
            "nifty_loop_duration_seconds",
            "Main event loop iteration duration",
            buckets=[0.01, 0.05, 0.1, 0.2, 0.5, 1.0],
        )
        self.tick_lag = Histogram(
            "nifty_tick_lag_seconds",
            "Lag between tick timestamp and processing",
            buckets=[0.01, 0.1, 0.5, 1.0, 2.0, 5.0],
        )
        self.risk_blocks = Counter(
            "nifty_risk_blocks_total",
            "Signals blocked by risk manager",
            ["reason"],
        )
        self.loop_errors = Counter(
            "nifty_loop_errors_total",
            "Main loop exceptions",
        )
        self.warmup_status = Gauge(
            "nifty_warmup_complete",
            "1 when warmup is complete, 0 otherwise",
        )
        self.daily_trades = Gauge(
            "nifty_daily_trades",
            "Number of trades today",
        )

    def start_server(self, port: int = 9090) -> None:
        start_http_server(port)


METRICS = BotMetrics()
