meta:
  version: 1
  name: "nifty_scalper_default"

windows:
  timezone: "Asia/Kolkata"
  trading:
    - { days: [1,2,3,4,5], start: "09:25", end: "15:05" }
  no_trade:
    expiry_tue_late:
      enabled: true
      start: "14:45"
      end:   "15:30"

gates:
  atr_pct_min: 0.025
  atr_pct_max: 2.00
  score_trend_min: 9
  score_range_min: 8
  mtf_confirm: true
  iv_percentile_limit: 85   # block if IVpct > limit AND score below trend min+1
  adx_min_trend: 18         # require ADX≥18 in TREND regime

micro:
  max_spread_pct_regular: 0.35
  max_spread_pct_open: 0.45
  max_spread_pct_last20m: 0.45
  depth_multiplier: 5
  depth_min_lots: 1

thresholds:
  min_atr_pct_nifty: 0.02
  min_atr_pct_banknifty: 0.04

options:
  delta_target: 0.40           # target absolute delta
  delta_band: 0.05             # acceptable |delta-target|
  delta_enable_score: 10       # only use delta-target when plan.score >= this
  min_oi: 500000
  max_median_spread_pct: 0.35
  delta_min: 0.35
  delta_max: 0.60
  re_atm_drift_pct: 0.35

lifecycle:
  tp1_R_min: 1.00
  tp1_R_max: 1.10
  tp1_partial: 0.6
  tp2_R_trend: 1.80
  tp2_R_range: 1.40
  trail_atr_mult: 0.80
  time_stop_min: 12
  gamma_mode:
    enabled: true
    tue_after: "14:45"
    tp2_R_cap: 1.40
    trail_atr_mult: 0.60
    time_stop_min: 8

risk:
  per_trade_pct_max: 0.60    # % of CURRENT equity per trade (example: 0.60 = 0.6%)
  max_consec_losses: 3
  cooldown_min: 20

rr_threshold: 1.5            # set to null to disable

warmup:
  min_bars_required: 20
  indicator_min_bars: 14
  mtf_min_bars: 21

debug:
  lower_score_temp: false

