from pathlib import Path

# One-shot TDD transform; removed after the validated production change lands.
runner_path = Path("src/nifty_scalper_bot/strategies/runner.py")
runner = runner_path.read_text()
old = '''                    plan = TradePlan(\n                        symbol=symbol,\n                        side=side,\n                        quantity=normalized_qty,\n                        entry_price=order_price,\n                        stop_loss=stop_loss,\n                        take_profit=take_profit,\n                        strategy_name="runner",\n                        tag=f"runner_{side.lower()}",\n                        allow_market_entry=False,\n                        intent="ENTRY",\n                        intended_position_side="LONG" if side == "BUY" else "SHORT",\n                    )'''
new = '''                    decision_ts = float(timestamp.timestamp())\n                    plan = TradePlan(\n                        symbol=symbol,\n                        side=side,\n                        quantity=normalized_qty,\n                        entry_price=order_price,\n                        stop_loss=stop_loss,\n                        take_profit=take_profit,\n                        strategy_name="runner",\n                        tag=f"runner_{side.lower()}",\n                        max_signal_age_seconds=safe_positive_float_env(\n                            "LIVE_ENTRY_MAX_SIGNAL_AGE_SECONDS", 5.0, minimum=0.1\n                        ),\n                        max_entry_drift_pct=safe_positive_float_env(\n                            "LIVE_ENTRY_MAX_ADVERSE_DRIFT_PCT", 1.0, minimum=0.05\n                        ),\n                        allow_market_entry=False,\n                        intent="ENTRY",\n                        intended_position_side="LONG" if side == "BUY" else "SHORT",\n                        trade_provenance={\n                            **dict(metadata or {}),\n                            "decision_ts": decision_ts,\n                            "decision_reference_price": float(price),\n                        },\n                    )'''
if old not in runner:
    raise SystemExit("runner TradePlan construction block not found")
runner_path.write_text(runner.replace(old, new, 1))

test_path = Path("tests/strategies/test_runner_final_snapshot_freshness_contract.py")
test_path.write_text('''from pathlib import Path\n\n\ndef test_runner_arms_existing_final_snapshot_freshness_contract() -> None:\n    source = Path("src/nifty_scalper_bot/strategies/runner.py").read_text()\n    assert '"LIVE_ENTRY_MAX_SIGNAL_AGE_SECONDS", 5.0, minimum=0.1' in source\n    assert '"LIVE_ENTRY_MAX_ADVERSE_DRIFT_PCT", 1.0, minimum=0.05' in source\n    assert '"decision_ts": decision_ts' in source\n    assert '"decision_reference_price": float(price)' in source\n\n\ndef test_freshness_is_armed_on_entry_plan_not_as_new_execution_path() -> None:\n    source = Path("src/nifty_scalper_bot/strategies/runner.py").read_text()\n    block_start = source.index("decision_ts = float(timestamp.timestamp())")\n    block_end = source.index("submit_result = self._order_manager.submit_trade_plan_result(plan)", block_start)\n    block = source[block_start:block_end]\n    assert 'intent="ENTRY"' in block\n    assert "max_signal_age_seconds=" in block\n    assert "max_entry_drift_pct=" in block\n    assert ".place_order(" not in block\n''')
