name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r requirements-app.txt || true
      - run: pip install ruff==0.6.9 black==24.8.0 mypy==1.11.1
      - run: ruff check .
      - run: black --check .
      - run: mypy src || true

  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Kolkata
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUTF8: "1"

      # ✅ Never trade live in CI
      ENABLE_LIVE_TRADING: "false"
      ENABLE_TRADING: "false"
      SKIP_BROKER_VALIDATION: "true"
      RUN_BACKTEST: "0"
      DATA__WARMUP_DISABLE: "true"
      EXPOSURE_BASIS: "premium"

      # ✅ Dummy creds to satisfy settings
      TELEGRAM__BOT_TOKEN: "test"
      TELEGRAM__CHAT_ID: "0"
      ZERODHA__API_KEY: "test"
      ZERODHA__API_SECRET: "test"
      ZERODHA__ACCESS_TOKEN: "test"

      # ✅ Coverage gate (tuneable)
      CI_COV_MIN: "75"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r requirements-app.txt || true
      - run: pip install pytest pytest-cov
      - run: pip install -r requirements-dev.txt || true
      - name: Run tests (skip slow/integration) with coverage
        run: |
          if [ -x ./run_checks.sh ]; then
            CI_COV_MIN="${CI_COV_MIN}" RUN_BACKTEST=0 ENABLE_LIVE_TRADING=false SKIP_BROKER_VALIDATION=true ./run_checks.sh || true
          fi
          pytest -m "not slow and not integration" --cov=src --cov-report=term-missing --cov-fail-under=${CI_COV_MIN}
