name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy

      - name: Lint with ruff
        run: |
          ruff --format=github .

      - name: Check formatting with ruff
        run: |
          ruff format --check .

      - name: Type check with mypy
        run: |
          mypy src/

      - name: Test with pytest
        run: |
          pytest
