name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install flake8 mypy pandas kiteconnect flask
      - name: Lint
        run: |
          flake8 src || true
      - name: Type check
        run: |
          mypy --ignore-missing-imports src || true
      - name: Smoke test (import)
        run: |
          python - <<'PY'
import importlib
for m in [
  "src.data_streaming.realtime_trader",
  "src.notifications.telegram_controller",
  "src.utils.strike_selector",
  "src.risk.position_sizing",
  "src.main",
]:
    try:
        importlib.import_module(m)
        print("OK", m)
    except Exception as e:
        print("FAIL", m, e)
          PY