name: Python CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.6.2 mypy==1.10.0 pytest==8.2.0
      - name: Ruff check (won't fail build)
        run: |
          ruff check src --output-format=github --exit-zero
      - name: Ruff format check (won't fail build)
        run: |
          ruff format --check src || true
      - name: Mypy type check (won't fail build)
        run: |
          mypy src || true
      - name: Run tests (won't fail build)
        run: |
          pytest -q || echo "Tests failed (non-blocking)"
